token: discordtoken
filters:
  keywords:
    - 3090
    - 3080
    - 3070
    - 3060
  blacklist:
    #If you don't want any value in the blacklist set it to null, otherwise replace it with the words you want to blacklist
    - null
various:
  playBellSound: True
channels:
  - 123456789123456789
  - 123456789123456789
  - 123456789123456789
